---
spring:
     profiles: docker
     datasource:
              driverClassName: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://localhost:3306/crs
              username: crs_user
              password: crs_user
---
spring: 
      jpa: 
         hibernate.ddl-auto: none
         database: mysql
         database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
         
---
           
#spring:
#      jpa: 
#         properties:
#                   hibernate: 
#                            format_sql: true
#---
#spring:
#       datasource:
#                 initialization-mode: always
#
#---
#
#
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: crs_db_create.sql
#---

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring:
       servlet: 
               multipart:
                         enabled: true
                         file-size-threshold: 2KB
                         max-file-size: 200MB
                         max-request-size: 215MB

---

file:
      upload-dir: ./uploads

#actuator

management:
         endpoints:
                 web:
                   base-path: /management
---
management:
           endpoints:
                     web:
                          exposure:
                                  include : "*"

---
# admin client
#spring.boot.admin.client.instance.service-base-url = http://localhost:8080
spring:
       application:
                  name : crime-reporting-system
---
spring: 
       boot: 
            admin:
                  client:
                         url : http://crsadmin.herokuapp.com
